Eve.EveAuthTool.GUI.Web/Controllers/DiscordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Discord;
using Discord.Rest;
using Eve.ESI.Standard.Account;
using Eve.EveAuthTool.GUI.Web.Models.Discord;
using Eve.EveAuthTool.Standard;
using Eve.EveAuthTool.Standard.Discord.Configuration;
using Eve.EveAuthTool.Standard.Discord.Configuration.Tenant;
using Eve.EveAuthTool.Standard.Discord.Service;
using Eve.EveAuthTool.Standard.Discord.Service.Module;
using Eve.EveAuthTool.Standard.Discord.Service.Providers;
using Eve.EveAuthTool.Standard.Helpers;
using Eve.EveAuthTool.Standard.Security.Middleware;
using Eve.EveAuthTool.Standard.Security.Rules;
using Gware.Standard.Collections.Generic;
using Gware.Standard.Web.OAuth;
using Gware.Standard.Web.Tenancy.Routing;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Gware.Standard.Web.Tenancy.Configuration;

namespace Eve.EveAuthTool.GUI.Web.Controllers
{
    [Authorize]
    [TenantRequired]
    public class DiscordController : Helpers.EveAuthBaseController<DiscordController>
    {
        private readonly OnceLoadedValue<string> m_linkString = new OnceLoadedValue<string>();
  
        public ulong? LinkedGuildID
        {
            get
            {
                ulong? retVal = null;
                if(ulong.TryParse(LinkedGuildString,out ulong id))
                {
                    retVal = id;
                }
                return retVal;
            }
        }
        public string LinkedGuildString
        {
            get
            {
                m_linkString.Load = () => TenantConfiguration.GetLink(CurrentTenant.Id, (byte)eTenantLinkType.Discord);
                return m_linkString.Value;
            }
        }
        public bool IsGuildLinked
        {
            get
            {
                return LinkedGuildID.HasValue ;
            }
        }
        
        public IArgumentsStore<DiscordLinkParameter> DiscordLinkStore { get; }
        public IDiscordBotConfiguration DiscordConfiguration { get; }
        public IArgumentsStore<OAuthRequestArguments> OAuthArgStore { get; }
        public IDiscordBot DiscordBot { get; }

        public DiscordController(IDiscordBot bot,ILogger<DiscordController> logger,IArgumentsStore<OAuthRequestArguments> oauthArgsStore,IDiscordBotConfiguration discordConfiguration,IArgumentsStore<DiscordLinkParameter> discordLinkStore, 
            ISingleParameters singles,IScopeParameters scopes)
            :base(logger,singles,scopes)
        {
            DiscordBot = bot;
            DiscordLinkStore = discordLinkStore;
            DiscordConfiguration = discordConfiguration;
            OAuthArgStore = oauthArgsStore;
        }
        private List<Models.Discord.DiscordRole> GetAllRoles(IGuild currentGuild)
        {
            List<Models.Discord.DiscordRole> allRoles = new List<Models.Discord.DiscordRole>();
            
            foreach (IRole role in currentGuild.Roles)
            {
                allRoles.Add(new Models.Discord.DiscordRole()
                {
                    ID = role.Id,
                    Name = role.Name
                });
            }
            return allRoles;
        }
        private async Task<List<Models.Discord.DiscordInvite>> GetInvites(IGuild currentGuild)
        {
            List<Models.Discord.DiscordInvite> allRoles = new List<Models.Discord.DiscordInvite>();
            IReadOnlyCollection<IInviteMetadata> invites = await currentGuild.GetInvitesAsync();
            foreach (IInviteMetadata invite in invites)
            {
                if (!invite.IsRevoked && !invite.IsTemporary)
                {
                    allRoles.Add(new Models.Discord.DiscordInvite()
                    {
                        ID = invite.Id,
                        Url = invite.Url
                    });
                }
                
            }
            return allRoles;
        }
        [HttpPost]
        [Authorize(Roles ="Manage")]
        public IActionResult UpdateLinkConfiguration(LinkedInfo info)
        {
            UserConfiguration.SetValue(Standard.Configuration.eUserSetting.UpdateDiscordImage, info.UpdateGuildImage);
            UserConfiguration.SetValue(Standard.Configuration.eUserSetting.UpdateDiscordName, info.UpdateGuildName);

            return RedirectToAction("Index");
        }

        [Authorize(Roles ="Manage")]
        public async Task<IActionResult> Index()
        {
            if (IsGuildLinked)
            {
                IGuild currentGuild = await DiscordBot.GetGuild(LinkedGuildID.Value);
                return View("LinkedIndex", new Models.Discord.LinkedInfo()
                {
                    GuildName = currentGuild.Name,
                    UpdateGuildImage = UserConfiguration.GetBoolean(Standard.Configuration.eUserSetting.UpdateDiscordImage),
                    UpdateGuildName = UserConfiguration.GetBoolean(Standard.Configuration.eUserSetting.UpdateDiscordName),
                    Configurations = Models.Discord.DiscordConfiguration.CreateFrom<Models.Discord.DiscordConfiguration>(DiscordRoleConfiguration.All(TenantController), GetAllRoles(currentGuild),await GetInvites(currentGuild))
                });

            }
            else
            {
                return View("UnlinkedIndex", new Models.Discord.UnlinkedInfo()
                {
                    AddBotUrl = DiscordConfiguration.GetAddBotUrl(),
                    CommandPrefix = DiscordConfiguration.CommandPrefix
                });
            }
            
        }
        [HttpGet]
        [Authorize(Roles = "Manage")]
        public async Task<IActionResult> EditConfiguration(long configID)
        {
            DiscordRoleConfiguration config = DiscordRoleConfiguration.Get<DiscordRoleConfiguration>(TenantController, configID);
            if(config == null)
            {
                config = new DiscordRoleConfiguration()
                {
                    Name = "New Discord Configuration"
                };
            }
            IGuild currentGuild = await DiscordBot.GetGuild(LinkedGuildID.Value); ;

            List<Models.Discord.DiscordInvite> invites = await GetInvites(currentGuild);
            Models.Discord.EditDiscordConfiguration configuration = Models.Discord.DiscordConfiguration.CreateFrom<Models.Discord.EditDiscordConfiguration>(config, GetAllRoles(currentGuild), invites);
            configuration.Invites = invites;
            return View(configuration);
        }
        [HttpPost]
        [Authorize(Roles = "Manage")]
        public IActionResult EditConfiguration(Models.Discord.DiscordConfiguration config)
        {
            DiscordRoleConfiguration roleConfig = config.Create();
            roleConfig.Save(TenantController);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Manage")]
        public IActionResult GenerateLink()
        {
            return new JsonResult(DiscordLinkStore.StoreArguments(new DiscordLinkParameter(CurrentTenant.Id)));
        }
        public async Task<IUser> GetDiscordUser(string token)
        {
            DiscordRestClient client = CreateDiscordClient();
            await client.LoginAsync(TokenType.Bearer, token);
            IUser retVal = client.CurrentUser;
            await client.LogoutAsync();
            return retVal;
        }
        private DiscordRestClient CreateDiscordClient()
        {
            DiscordRestClient client = new DiscordRestClient(new DiscordRestConfig()
            {
                LogLevel = LogSeverity.Info
            });
            client.Log += x =>
            {
                if (x.Severity == LogSeverity.Error)
                {
                    Logger.LogError(x.Exception, "Discord Rest client exception");
                }
                else
                {
                    Logger.LogInformation(x.Message);
                }

                return Task.CompletedTask;
            };
            return client;
        }
        public IActionResult QuickAuthDiscord()
        {
            if (IsGuildLinked)
            {
                DiscordOAuthRequestArguments args = HttpContext.GetLocalArguments<DiscordOAuthRequestArguments>(
                currentTenant: CurrentTenant,
                redirectPath: "Discord/LinkDiscordAccount");

                return Redirect(args.GetAuthenticationUrl(
                    state: OAuthArgStore.StoreArguments(args),
                    config: DiscordConfiguration));
            }
            else
            {
                return View("Error", new Models.Shared.ErrorModel() { Message = "No Discord link" });
            }
            
        }
        [Authorize]
        public async Task<IActionResult> LinkDiscordAccount([FromServices]IDiscordLinkProvider linkProvider,string state)
        {
            DiscordOAuthRequestArguments arguments = OAuthArgStore.ReCallArguments(state) as DiscordOAuthRequestArguments;
            try
            {
                if (arguments != null)
                {
                    if (IsGuildLinked)
                    {
                        Standard.Discord.Authentication.AuthenticationToken token = await Standard.Discord.Authentication.AuthenticationToken.RequestToken(DiscordConfiguration, arguments.Code);
                        if (token != null)
                        {
                            DiscordRestClient client = CreateDiscordClient();
                            try
                            {
                                await client.LoginAsync(TokenType.Bearer, token.Access_Token);
                                if (client.CurrentUser != null)
                                {
                                    if (linkProvider != null)
                                    {

Eve.EveAuthTool.GUI.Web/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Eve.ESI.Standard;
using Eve.ESI.Standard.AuthenticatedData;
using Eve.ESI.Standard.DataItem.Corporation;
using Eve.ESI.Standard.DataItem.Search;
using Eve.EveAuthTool.Standard.Security.Middleware;
using Eve.EveAuthTool.GUI.Web.Models.Management;
using Eve.EveAuthTool.Standard.Security.Rules;
using Gware.Standard.Web.Tenancy.Routing;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Eve.EveAuthTool.Standard.Discord.Configuration.Tenant;
using Microsoft.Extensions.Logging;
using Eve.EveAuthTool.Standard.Helpers;

namespace Eve.EveAuthTool.GUI.Web.Controllers
{
    [Authorize]
    [TenantRequired]
    public class ManagementController : Helpers.EveAuthBaseController<ManagementController>
    {
        public ManagementController(ILogger<ManagementController> logger,
            ISingleParameters singles, IScopeParameters scopes)
            : base(logger, singles, scopes)
        {

        }
        [Authorize(Roles="Manage")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Manage")]
        public IActionResult Rules()
        {
            return View(AuthRule.InOrder(TenantController));
        }

        [Authorize(Roles = "Manage")]
        public IActionResult Roles()
        {
            return View(RoleModel.CreateFrom(Role.All(TenantController), DiscordRoleConfiguration.All(TenantController)));
        }

        [HttpGet]
        [Authorize(Roles = "Manage")]
        public IActionResult EditRule(long ruleID)
        {
            AuthRule rule = AuthRule.Get<AuthRule>(TenantController, ruleID);
            if(rule == null)
            {
                rule = new AuthRule()
                {
                    Name = "New Rule"
                };
            }
            
            return View(rule);
        }
        [HttpGet]
        [Authorize(Roles = "Manage")]
        public IActionResult EditRole(long roleID)
        {
            //role.Save(TenantController);
            Role role = Role.Get<Role>(TenantController, roleID);
            if(role == null)
            {
                role = new Role()
                {
                    Name = "New Role"
                };
            }

            EditRoleModel model = RoleModel.CreateFrom<EditRoleModel>(role, DiscordRoleConfiguration.Get<DiscordRoleConfiguration>(TenantController, role.DiscordRoleConfigurationID));
            model.AllConfigurations = Models.Discord.DiscordConfiguration.CreateFrom<Models.Discord.DiscordConfiguration>(DiscordRoleConfiguration.All(TenantController),new List<Models.Discord.DiscordRole>(),new List<Models.Discord.DiscordInvite>());
            return View("EditRole", model);
        }
        [HttpPost]
        [Authorize(Roles = "Manage")]
        public IActionResult EditRole(RoleModel role)
        {
            Role systemRole = Role.Get<Role>(TenantController, role.Id);
            if(systemRole == null)
            {
                systemRole = new Role();
            }
            systemRole.Name = role.Name;
            systemRole.Permissions = Standard.Security.eRulePermission.None;
            if (role.Register)
            {
                systemRole.Permissions |= Standard.Security.eRulePermission.Register;
            }
            if (role.Manage)
            {
                systemRole.Permissions |= Standard.Security.eRulePermission.Manage;
            }
            systemRole.DiscordRoleConfigurationID = role.DiscordRoleConfigurationID;
            systemRole.Save(TenantController);
            return RedirectToAction("Roles");
        }
        
        [HttpPost]
        [Authorize(Roles = "Manage")]
        public IActionResult EditRule(AuthRule rule)
        {
            rule.Save(TenantController);
            return RedirectToAction("Rules");
        }

        [HttpPost]
        [Authorize(Roles = "Manage")]
        public IActionResult DeleteRule(long ruleID)
        {
            AuthRule.Delete<AuthRule>(TenantController, ruleID);
            return RedirectToAction("Rules");
        }
        [HttpGet]
        public IActionResult FormEntityRule(long entityID,int searchType,int index)
        {
            return PartialView("IndexedAuthRuleRelationship", new IndexAuthRuleRelationship(index, AuthRuleRelationship.GetStaticRelationship(entityID, SearchResults.SearchTypeToEntityType((eSearchEntity)searchType))));
        }
        [HttpGet]
        public IActionResult FormRoleRule(long roleID,int location, int index)
        {
            return PartialView("IndexedAuthRuleRelationship", new IndexAuthRuleRelationship(index, 
                AuthRuleRelationship.GetRelationshipRule(roleID,eESIEntityType.role,
                ESI.Standard.DataItem.Helper.RoleLocationToRelationship((ESI.Standard.DataItem.eRoleLocation)location))));
        }
        [HttpGet]
        public IActionResult FormStandingRule(long entityID, int entityType,int standingType, int index)
        {
            return PartialView("IndexedAuthRuleRelationship", new IndexAuthRuleRelationship(index,
                AuthRuleRelationship.GetRelationshipRule(entityID, (eESIEntityType)entityType,
                ESI.Standard.DataItem.Helper.StandingToRelationship((eESIStanding)standingType))));
        }

        [HttpGet]
        public IActionResult FormTitleRole(int corporationID,int titleID, int index)
        {
            return PartialView("IndexedAuthRuleRelationship", new IndexAuthRuleRelationship(index,
                AuthRuleRelationship.GetRelationshipRule(titleID,eESIEntityType.title,eESIEntityRelationship.Title,corporationID,eESIEntityType.corporation)));
        }
        [HttpGet]
        [Authorize(Roles = "Manage")]
        public async Task<IActionResult> CorporationTitles(int corporationID)
        {
            List<CorporationTitle> retVal = new List<CorporationTitle>();
            AuthenticatedEntity entity = AuthenticatedEntity.GetForEntity(ESIConfiguration, TenantController, Cache, PublicDataProvider, corporationID, eESIEntityType.corporation);
            if(entity != null)
            {
                ESICollectionCallResponse<CorporationTitle> titles = await entity.GetCorporationTitles();
                retVal.AddRange(titles.Data.Where(x => !string.IsNullOrWhiteSpace(x.Name)));
            }
            return PartialView("CorporationTitles", retVal);
        }
    }
}

Eve.EveAuthTool.GUI.Web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Eve.ESI.Standard;
using Eve.ESI.Standard.DataItem.Search;
using Eve.EveAuthTool.Standard.Security.Middleware;
using Eve.EveAuthTool.GUI.Web.Models.Search;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Eve.EveAuthTool.Standard.Helpers;

namespace Eve.EveAuthTool.GUI.Web.Controllers
{
    public class SearchController : Helpers.EveAuthBaseController<SearchController>
    {

        public SearchController(ILogger<SearchController> logger,
            ISingleParameters singles, IScopeParameters scopes)
            : base(logger, singles, scopes)
        {

        }

        public async Task<IActionResult> SearchEntities(string query, bool oldData , string resultID)
        {
            ESICallResponse<SearchResults> result = await PublicDataProvider.Search(query, eSearchEntity.alliance | eSearchEntity.corporation | eSearchEntity.character | eSearchEntity.faction);
            if (result.HasData)
            {
                return PartialView("SearchResult", new SearchResult(Cache,PublicDataProvider, result.Data,oldData, resultID));
            }
            return new JsonResult("No Results");
        }
    }
}

Eve.EveAuthTool.GUI.Web/Views/Management/CorporationTitles.cshtml
@model IEnumerable<Eve.ESI.Standard.DataItem.Corporation.CorporationTitle>

@if (Model.Count<Eve.ESI.Standard.DataItem.Corporation.CorporationTitle>() == 0)
{
    <div>
        No Titles Found
    </div>
}
else
{
    foreach(var title in Model)
    {
        <div class="corporation-title-result" data-title-id="@title.TitleId">@title.Name</div>
    }
}

Eve.EveAuthTool.GUI.Web/Views/Management/EditRule.cshtml
@model Eve.EveAuthTool.Standard.Security.Rules.AuthRule
@inject Eve.EveAuthTool.Standard.Helpers.ISingleParameters singles
@inject Eve.EveAuthTool.Standard.Helpers.IScopeParameters scoped
@{
    ViewData["Title"] = "EditRule";
    var roleObjectList = new List<Object>();
    foreach (var role in Eve.EveAuthTool.Standard.Security.Rules.Role.All(scoped.TenantController))
    {
        roleObjectList.Add(new { id = role.Id, text = role.Name });
    }

    var roleSelectList = new SelectList(roleObjectList, "id", "text", Model.RoleId);


    var roleLocationList = new List<Object>();
    foreach (Eve.ESI.Standard.DataItem.eRoleLocation location in Enum.GetValues(typeof(Eve.ESI.Standard.DataItem.eRoleLocation)))
    {
        roleLocationList.Add(new { id = (int)location, text = Gware.Standard.Data.EnumDisplayAttribute.GetEnumString(location) });
    }

    var allEntities = Eve.ESI.Standard.AuthenticatedData.AuthenticatedEntity.GetAll(singles.ESIConfiguration, scoped.TenantController, singles.Cache, singles.PublicDataProvider);

    var breadcrumbs = new List<Breadcrumb>()
{
new Breadcrumb() {Controller="Management",Action="Index", Text="Management"},
new Breadcrumb() {Controller="Management",Action="Rules", Text="Rules"}
};
}
@section Breadcrumbs{
    <partial name="breadcrumbs" model="breadcrumbs">
}
@section Styles{

    <link rel="stylesheet" href="~/css/search.css" />
    <link rel="stylesheet" href="~/css/spinner.css" />
    <link rel="stylesheet" href="~/css/rule.css" />

}

@section Scripts{
    <script src="~/js/management.js"></script>
    <script src="~/js/search.js"></script>
}

<form class="content-box theme-border width-50 center" asp-action="EditRule" asp-controller="Management">
    <div>
        Name - @Html.TextBoxFor(x => Model.Name)
        Role - @Html.DropDownListFor(x => x.RoleId, roleSelectList)
        Priority - @Html.EditorFor(x => Model.Ordinal, new { htmlAttributes = new { @type = "number", @min = "0", @step = "1", @value = "0" } })
        Match All - @Html.CheckBoxFor(x => Model.MatchAll)
    </div>
    @Html.HiddenFor(x => Model.Id)
    <div class="standard-padding-top">
        <div class="inline-block">Relationships</div> <div onclick="showDialog('addRelationshipDialogContainer')" class="inline-block"><i class="fas fa-plus"></i></div>
    </div>
    <hr />
    <div id="relationships">
        @for (int i = 0; i < Model.Relationships.Count; i++)
        {
            var relationship = Model.Relationships[i];

            <partial name="IndexedAuthRuleRelationship" model="new Eve.EveAuthTool.GUI.Web.Models.Management.IndexAuthRuleRelationship(i, relationship)" />
        }
    </div>


    <button type="submit">Save</button>
</form>
<div id="addRelationshipDialogContainer" class="dialog-container">
    <div id="relationshipDialog" class="dialog">
        <div class="header">
            Add relationship
            <hr />
        </div>
        <ejs-tab id="relationshipTab">
            <e-tab-tabitems>
                <e-tab-tabitem header="@(new Syncfusion.EJ2.Navigations.TabHeader { Text = "Entity" })" content="#entitySearch"></e-tab-tabitem>
                <e-tab-tabitem header="@(new Syncfusion.EJ2.Navigations.TabHeader { Text = "Roles" })" content="#role"></e-tab-tabitem>
                <e-tab-tabitem header="@(new Syncfusion.EJ2.Navigations.TabHeader { Text = "Titles" })" content="#titles"></e-tab-tabitem>
                <e-tab-tabitem header="@(new Syncfusion.EJ2.Navigations.TabHeader { Text = "Standings" })" content="#standing"></e-tab-tabitem>
            </e-tab-tabitems>
        </ejs-tab>
        <div id="entitySearch" class="entity-search" style="display:none">
            <form id="entitySearchForm" asp-controller="Search" asp-action="SearchEntities"
                  data-ajax-begin="onEntitySearchBegin" data-ajax-complete="onEntitySearchComplete"
                  data-ajax-failure="onEntitySearchFailed" data-ajax-success="onEntitySearchSuccess"
                  data-ajax="true" data-ajax-method="POST"
                  asp-route-resultID="entitySearchResult" asp-route-oldData="true">
                Search: <input type="text" name="query" />
                <button type="submit">Submit</button>
            </form>
            <div id="entitySearchWait" class="line-spinner hidden">
                <div class="rect1"></div>
                <div class="rect2"></div>
                <div class="rect3"></div>
                <div class="rect4"></div>
                <div class="rect5"></div>
            </div>
            <div id="entitySearchResults"></div>
        </div>
        <div id="role" class="entity-role" style="display:none">
            <div>
                <ejs-dropdownlist id="roleLocations" dataSource="roleLocationList" placeholder="Select a location" index="0" popupHeight="220px">
                    <e-dropdownlist-fields text="text" value="id"></e-dropdownlist-fields>
                </ejs-dropdownlist>
            </div>
            <div>
                <ejs-accordion id="searchResultsAccordion">
                    <e-accordion-accordionitems>
                        @foreach (Eve.ESI.Standard.DataItem.eESIRoleGroup group in Eve.ESI.Standard.DataItem.Helper.GroupedRoles.Keys)
                        {
                            <e-accordion-accordionitem header="@(Gware.Standard.Data.EnumDisplayAttribute.GetEnumString(group))" content="#@group"></e-accordion-accordionitem>
                        }
                    </e-accordion-accordionitems>
                </ejs-accordion>

                @foreach (Eve.ESI.Standard.DataItem.eESIRoleGroup group in Eve.ESI.Standard.DataItem.Helper.GroupedRoles.Keys)
                {
                    <div id="@group" style="display:none">
                        @foreach (Eve.ESI.Standard.DataItem.eESIRole role in Eve.ESI.Standard.DataItem.Helper.GroupedRoles[group])
                        {
                            <div onclick="AddRole(@((long)role))" class="role-item esi-role">@(Gware.Standard.Data.EnumDisplayAttribute.GetEnumString(role))</div>
                        }
                    </div>
                }
            </div>

        </div>
        <div id="standing" class="entity-standing" style="display:none">
            <div>
                <ejs-accordion id="standingAccordion">
                    <e-accordion-accordionitems>
                        @foreach (var entityType in allEntities.Keys)
                        {
                            <e-accordion-accordionitem header="@(Gware.Standard.Data.EnumDisplayAttribute.GetEnumString(entityType))" content="#@entityType"></e-accordion-accordionitem>
                        }
                    </e-accordion-accordionitems>
                </ejs-accordion>

                @foreach (var entityType in allEntities.Keys)
                {

                    <div id="@entityType" style="display:none">
                        @foreach (var entity in allEntities[entityType])
                        {
                            <div class="standing-item">
                                <img src="@singles.ESIConfiguration.GetImageSource(entityType,entity.EntityID,32)" />
                                <div class="name">@( await singles.PublicDataProvider.GetEntityName(entityType, entity.EntityID))</div>
                                <div class="e-btn-group">
                                    <ejs-button onclick="AddStanding(@entity.EntityID,@((int)entityType),4);" cssClass="e-small" id="@($"{entityType}{entity.EntityID}Excellent")" content="Excellent"></ejs-button>
                                    <ejs-button onclick="AddStanding(@entity.EntityID,@((int)entityType),3);" cssClass="e-small" id="@($"{entityType}{entity.EntityID}Good")" content="Good"></ejs-button>
                                    <ejs-button onclick="AddStanding(@entity.EntityID,@((int)entityType),0);" cssClass="e-small" id="@($"{entityType}{entity.EntityID}Neutral")" content="Neutral"></ejs-button>
                                    <ejs-button onclick="AddStanding(@entity.EntityID,@((int)entityType),2);" cssClass="e-small" id="@($"{entityType}{entity.EntityID}Bad")" content="Bad"></ejs-button>
                                    <ejs-button onclick="AddStanding(@entity.EntityID,@((int)entityType),1);" cssClass="e-small" id="@($"{entityType}{entity.EntityID}Terrible")" content="Terrible"></ejs-button>
                                </div>
                            </div>
                        }
                    </div>
                }
            </div>
        </div>
        <div id="titles" style="display:none;">
            @{
                var authenticatedCorporations = Eve.ESI.Standard.AuthenticatedData.AuthenticatedEntity.ForEntityType(singles.ESIConfiguration, scoped.TenantController, singles.Cache, singles.PublicDataProvider, Eve.ESI.Standard.eESIEntityType.corporation);
                var titleCorporationList = new List<Object>();
                foreach (var corp in authenticatedCorporations)
                {
                    titleCorporationList.Add(new { id = corp.EntityID, text = await singles.PublicDataProvider.GetEntityName(corp.EntityType, corp.EntityID) });
                }
            }
            <ejs-dropdownlist id="titleEntities" dataSource="titleCorporationList" placeholder="Select a Corporation" popupHeight="220px" change="OnTitleCorporationSelect">
                <e-dropdownlist-fields text="text" value="id"></e-dropdownlist-fields>
            </ejs-dropdownlist>
            <div id="titleWait" class="line-spinner hidden">
                <div class="rect1"></div>
                <div class="rect2"></div>
                <div class="rect3"></div>
                <div class="rect4"></div>
                <div class="rect5"></div>
            </div>
            <div id="titleResults"></div>
        </div>
    </div>
</div>

Eve.EveAuthTool.GUI.Web/Views/Management/Index.cshtml
@{
    ViewData["Title"] = "Management";
}

<div class="content-box theme-border width-50 center">
    <h3>Management</h3>
    <p>
        In order to make ESA as configurable as possible there are lots of ways that the system can be setup and it designed to be easy to add features to.
        The main problem with this is that it can look a little empty until the system is filled out with more features.
    </p>
    <p>
        To setup your system first visit the discord page to add and link ESA to your discord guild. When that is done you can create discord configurations that contain
        roles from your discord server that will be assigned to people.
    </p>

    <p>
        Next up you create ESA roles that allow you to link discord configuration to a set of permissions that will be assigned to users.
    </p>
    <p>
        The final part is to create the rules that choose what roles characters will be given.
    </p>
    <hr />
    <p>
        <a asp-action="Index" asp-controller="Discord">Discord</a> - Manage your discord link and configurations so that they can be assigned to roles.
    </p>
    <p>
        <a asp-action="Roles" asp-controller="Management">Roles</a> - Manage the permissions and configurations assigned to roles.
    </p>
    <p>
        <a asp-action="Rules" asp-controller="Management">Rules</a> - Manage the rules that assign people roles.
    </p>
</div>